---
- hosts: all
  pre_tasks:
    - name: Verify Ansible meets flatpak module version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.7.6', '>=')"
        msg: >
          "You must update Ansible to at least 2.7.6 to use flatpak module"

- name: assign role desktop to localhost
  hosts: localhost
  roles:
  - desktop
