---
- name: Install Fedora packages
  dnf:
    pkg:
      - baobab
      - docker
      - exfat-utils
      - fuse-exfat
      - flatpak
      - firefox
      - gnome-disk-utility
      - mediainfo-gui
      - mpv
      - python3-pip
      - gedit
      - mkvtoolnix-gui
      - dconf-editor
      - steam
      - VirtualBox
      - gnome-system-monitor
      - curl
      - git
      - nmap
      - npm
      - vim-enhanced
    state: latest

- name: Install Tusk RPM
  dnf:
    name: 'https://github.com/klaussinani/tusk/releases/download/v0.22.0/tusk-0.22.0.x86_64.rpm'
    state: present

- name: Install chezmoi RPM
  dnf:
    name: 'https://github.com/twpayne/chezmoi/releases/download/v1.3.0/chezmoi-1.3.0-460-x86_64.rpm'
    state: present
