---
- name: Install Fedora packages
  dnf:
    pkg:
      - baobab
      - devscripts
      - exfat-utils
      - fuse-exfat
      - firefox
      - gnome-disk-utility
      - mediainfo-gui
      - mpv
      - python3-pip
      - gedit
      - mkvtoolnix-gui
      - dconf-editor
      - steam
#     - VirtualBox
      - gnome-system-monitor
      - curl
      - git
      - nmap
      - npm
      - rpm-build
      - vim-enhanced
    state: latest

- name: Install Tusk RPM
  dnf:
    name: 'https://github.com/klaussinani/tusk/releases/download/v{{ tusk_version }}/tusk-{{ tusk_version }}.x86_64.rpm'
    state: present

- name: Install chezmoi RPM
  dnf:
    name: 'https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_version }}/chezmoi-{{ chezmoi_version }}-{{ chezmoi_revision }}-x86_64.rpm'
    state: present
