---

- name: Check / free disk space
  shell: df -h / | awk '{ print $4 }' | tail -n 1 | sed 's/.$//'
  register: free_disk_space
  changed_when: False

- fail:
    msg: "Not enough / free disk space! Only {{ free_disk_space.stdout }} GB"
  when: free_disk_space.stdout|int < 10

- import_tasks: fedora.yml
  when: ansible_os_family == "Fedora" or ansible_os_family == "Kaizen"

- import_tasks: ubuntu.yml
  when: ansible_os_family != "Fedora" and ansible_os_family != "Kaizen"

- import_tasks: docker.yml

- import_tasks: slack.yml

- import_tasks: tusk.yml

- name: Install youtube-dl
  pip:
    name: youtube-dl
    executable: pip3
    state: latest
