---

- import_tasks: fedora.yml
  when: ansible_os_family == "Fedora" or ansible_os_family == "Kaizen"

- import_tasks: ubuntu.yml
  when: ansible_os_family != "Fedora" and ansible_os_family != "Kaizen"

- import_tasks: docker.yml

- import_tasks: slack.yml

- import_tasks: tusk.yml

- name: Install youtube-dl
  pip:
    name: youtube-dl
    executable: pip3
    state: latest
