---

- import_tasks: fedora.yml
  when: ansible_os_family == "Fedora" or ansible_os_family == "Kaizen"

- import_tasks: ubuntu.yml
  when: ansible_os_family != "Fedora" and ansible_os_family != "Kaizen"

- import_tasks: docker.yml

- import_tasks: slack.yml

- name: Install youtube-dl
  pip:
    name: youtube-dl
    executable: pip3
    state: latest

- name: Create /var/shared
  file:
    path: /var/shared
    state: directory
    mode: 0750
    owner: codygarver
    group: codygarver
