---

- name: Add Slack repo
  template:
    src: slack.repo.j2
    dest: /etc/yum.repos.d/slack.repo
    owner: root
    group: root
    mod: 0644
  when: ansible_os_family == "Fedora" or ansible_os_family == "Kaizen"

- name: Install Slack
  dnf:
    name: slack
    state: present
  when: ansible_os_family == "Fedora" or ansible_os_family == "Kaizen"
