---

- name: Add flathub repository
  apt_repository:
    repo: ppa:alexlarsson/flatpak

- name: Install Ubuntu packages
  apt:
    pkg:
      - baobab
      - docker
      - exfat-utils
      - fuse-exfat
      - flatpak
      - firefox
      - gnome-disk-utility
      - mediainfo-gui
      - mpv
      - python3-pip
      - gedit
      - mkvtoolnix-gui
      - dconf-editor
      - steam
#      - virtualbox
      - gnome-system-monitor
      - curl
      - git
      - nmap
      - npm

- name: Install Tusk .deb
  apt:
    name: 'https://github.com/klaussinani/tusk/releases/download/v0.21.0/tusk_0.21.0_amd64.deb'
    state: present

- name: Install chezmoi .deb
  apt:
    name: 'https://github.com/twpayne/chezmoi/releases/download/v1.3.0/chezmoi_1.3.0-460_linux_amd64.deb'
    state: present