---

- name: Install Ubuntu packages
  apt:
    pkg: "{{ fedora_ubuntu_packages }}"
    state: latest

- name: Install Ubuntu packages
  apt:
    pkg: "{{ ubuntu_packages }}"
    state: latest

- name: Install chezmoi .deb
  apt:
    deb: 'https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_version }}/chezmoi_{{ chezmoi_version }}-{{ chezmoi_revision }}_linux_amd64.deb'
    state: present
