---

- name: Add flathub repository
  apt_repository:
    repo: ppa:alexlarsson/flatpak

- name: Install Ubuntu packages
  apt:
    pkg:
      - baobab
      - devscripts
      - exfat-utils
      - exfat-fuse
      - flatpak
      - firefox
      - gnome-disk-utility
      - mediainfo-gui
      - mpv
      - python3-pip
      - gedit
      - mkvtoolnix-gui
      - dconf-editor
      - steam
#      - virtualbox
      - gnome-system-monitor
      - curl
      - git
      - nmap
      - npm
      - vim

- name: Install Tusk .deb
  apt:
    deb: 'https://github.com/klaussinani/tusk/releases/download/v0.22.0/tusk_0.22.0_amd64.deb'
    state: present

- name: Install chezmoi .deb
  apt:
    deb: 'https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_version }}/chezmoi_{{ chezmoi_version }}-{{ chezmoi_revision }}_linux_amd64.deb'
    state: present

- name: Install Slack .deb
  apt:
    deb: 'https://downloads.slack-edge.com/linux_releases/slack-desktop-3.3.7-amd64.deb'
    state: present
